export const dateConstants = {
  months: {
    0: ['January', 'Января', 'Студзеня'],
    1: ['February', 'Февраля', 'Лютага'],
    2: ['March', 'Марта', 'Сакавіка'],
    3: ['April', 'Апреля', 'Красавіка'],
    4: ['May', 'Мая', 'Мая'],
    5: ['June', 'Июня', 'Чэрвеня'],
    6: ['July', 'Июля', 'Ліпеня'],
    7: ['August', 'Августа', 'Жніўня'],
    8: ['September', 'Сентября', 'Верасня'],
    9: ['October', 'Октября', 'Кастрычніка'],
    10: ['November', 'Ноября', 'Лістапада'],
    11: ['December', 'Декабря', 'Снежня'],
  },
  days: {
    0: ['Sunday', 'Воскресенье', 'Нядзеля'],
    1: ['Monday', 'Понедельник', 'Панядзелак'],
    2: ['Tuesday', 'Вторник', 'Аўторак'],
    3: ['Wednesday', 'Среда', 'Серада'],
    4: ['Thursday', 'Четверг', 'Чацвер'],
    5: ['Friday', 'Пятница', 'Пятніца'],
    6: ['Saturday', 'Суббота', 'Субота'],
  },
};

export const weatherConstants = {
  2: {
    200: 'навальніца з невялікім дажджом',
    201: 'навальніца з дажджом',
    202: 'навальніца з моцным дажджом',
    210: 'невялікая навальніца',
    211: 'навальніца',
    212: 'моцная навальніца',
    221: 'навальніца',
    230: 'навальніца з невялікай імглой',
    231: 'навальніца з імглой',
    232: 'навальніца з моцнай імглой',
    300: 'невялікая імгла',
    301: 'лёгкі дождж, імгла',
    302: 'кароткачасовы дождж',
    310: 'невялікая імгла з дажджом',
    311: 'лёгкі дождж',
    312: 'лёгкі інтэнсіўны дождж',
    313: 'кароткачасовы дождж з імглой',
    314: 'моцны кароткачасовы дождж з імглой',
    321: 'кароткачасовая імгла',
    500: 'лёгкі дождж',
    501: 'умераны дождж',
    502: 'моцны дождж',
    503: 'вельмі моцны дождж',
    504: 'лівень',
    511: 'дождж з градам',
    520: 'лёгкі кароткачасовы дождж',
    521: 'кароткачасовы дождж',
    522: 'моцны кароткачасовы дождж',
    531: 'кароткачасовыя дажджы',
    600: 'невялікі снег',
    601: 'снег',
    602: 'моцны снег',
    611: 'мокры снег',
    612: 'кароткачасовы мокры снег',
    615: 'лёгкі снег з дажджом',
    616: 'снег з дажджом',
    620: 'лёгкі кароткачасовы снег',
    621: 'кароткачасовы снег',
    622: 'моцны кароткачасовы снег',
    701: 'туман',
    711: 'дым',
    721: 'лёгкі туман',
    731: 'віхор пяску і пылу',
    741: 'туман',
    751: 'пясок',
    761: 'пыл',
    762: 'вулканічны попел',
    771: 'шквалы',
    781: 'тарнада',
    800: 'ясна',
    801: 'невялікая воблачнасць',
    802: 'воблачна',
    803: 'пераменная воблачнасць',
    804: 'пахмурна',
  },
  1: {
    200: 'гроза с небольшим дождем',
    201: 'гроза с дождем',
    202: 'гроза с проливным дождем',
    210: 'слабая гроза',
    211: 'гроза',
    212: 'сильная гроза',
    221: 'гроза',
    230: 'гроза со слабым туманом',
    231: 'гроза с туманом',
    232: 'гроза с сильным туманом',
    300: 'слабый туман',
    301: 'легкий дождь, туман',
    302: 'кратковременный дождь',
    310: 'легкий туман с дождем',
    311: 'легкий дождь',
    312: 'легкий сильный дождь',
    313: 'кратковременный дождь с туманом',
    314: 'сильный кратковременный дождь с туманом',
    321: 'кратковременный туман',
    500: 'легкий дождь',
    501: 'умеренный дождь',
    502: 'сильный дождь',
    503: 'очень сильный дождь',
    504: 'дождь',
    511: 'дождь с градом',
    520: 'легкий прерывистый дождь',
    521: 'кратковременный дождь',
    522: 'сильный прерывистый дождь',
    531: 'кратковременные дожди',
    600: 'легкий снег',
    601: 'снег',
    602: 'сильный снегопад',
    611: 'мокрый снег',
    612: 'кратковременный мокрый снег',
    615: 'легкий снег с дождем',
    616: 'снег с дождем',
    620: 'кратковременный легкий снег',
    621: 'кратковременный снег',
    622: 'кратковременный сильный снегопад',
    701: 'туман',
    711: 'дым',
    721: 'легкий туман',
    731: 'вихрь песка и пыли',
    741: 'туман',
    751: 'песок',
    761: 'пыль',
    762: 'вулканический пепел',
    771: 'шквалы',
    781: 'торнадо',
    800: 'ясно',
    801: 'слегка облачно',
    802: 'облачно',
    803: 'переменная облачность',
    804: 'пасмурно',
  },
  0: {
    200: 'thunderstorm with light rain',
    201: 'thunderstorm with rain',
    202: 'thunderstorm with heavy rain',
    210: 'light thunderstorm',
    211: 'thunderstorm',
    212: 'heavy thunderstorm',
    221: 'ragged thunderstorm',
    230: 'thunderstorm with light drizzle',
    231: 'thunderstorm with drizzle',
    232: 'thunderstorm with heavy drizzle',
    300: 'light intensity drizzle',
    301: 'drizzle',
    302: 'heavy intensity drizzle',
    310: 'light intensity drizzle rain',
    311: 'drizzle rain',
    312: 'heavy intensity drizzle rain',
    313: 'shower rain and drizzle',
    314: 'heavy shower rain and drizzle',
    321: 'shower drizzle',
    500: 'light rain',
    501: 'moderate rain',
    502: 'heavy intensity rain',
    503: 'very heavy rain',
    504: 'extreme rain',
    511: 'freezing rain',
    520: 'light intensity shower rain',
    521: 'shower rain',
    522: 'heavy intensity shower rain',
    531: 'ragged shower rain',
    600: 'light snow',
    601: 'Snow',
    602: 'Heavy snow',
    611: 'Sleet',
    612: 'Light shower sleet',
    615: 'Light rain and snow',
    616: 'Rain and snow',
    620: 'Light shower snow',
    621: 'Shower snow',
    622: 'Heavy shower snow',
    701: 'mist',
    711: 'Smoke',
    721: 'Haze',
    731: 'sand/ dust whirls',
    741: 'fog',
    751: 'sand',
    761: 'dust',
    762: 'volcanic ash',
    771: 'squalls',
    781: 'tornado',
    800: 'clear sky',
    801: 'few clouds',
    802: 'scattered clouds',
    803: 'broken clouds',
    804: 'overcast clouds',
  },
};

export const i18nConstants = {
  apparentTemp: ['Apparent Temperature:', 'Кажущаяся температура', 'Уяўная тэмпература:'],
  wind: ['Wind:', 'Скорость ветра:', 'Хуткасць ветру:'],
  humidity: ['Humidity:', 'Влажность:', 'Вільготнасць:'],
  latitude: ['Latitude: ', 'Широта: ', 'Шырата: '],
  longitude: ['Longitude: ', 'Долгота: ', 'Даўгата: '],
  speed: ['m/s', 'м/с', 'м/с'],
};

export const countries = {
  AB: 'Abkhazia',
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Åland Islands',
  AZ: 'Azerbaijan',
  Alpha2: 'На английском',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'Saint Barthélemy',
  BM: 'Bermuda',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia, plurinational state of',
  BQ: 'Bonaire, Sint Eustatius and Saba',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Cocos (Keeling) Islands',
  CD: 'Congo, Democratic Republic of the',
  CF: 'Central African Republic',
  CG: 'Congo',
  CH: 'Switzerland',
  CI: "Cote d'Ivoire",
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cape Verde',
  CW: 'Curaçao',
  CX: 'Christmas Island',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  EH: 'Western Sahara',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands (Malvinas)',
  FM: 'Micronesia, Federated States of',
  FO: 'Faroe Islands',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'French Guiana',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Greenland',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadeloupe',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GS: 'South Georgia and the South Sandwich Islands',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HM: 'Heard Island and McDonald Islands',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IN: 'India',
  IO: 'British Indian Ocean Territory',
  IQ: 'Iraq',
  IR: 'Iran, Islamic Republic of',
  IS: 'Iceland',
  IT: 'Italy',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KP: "Korea, Democratic People's republic of",
  KR: 'Korea, Republic of',
  KW: 'Kuwait',
  KY: 'Cayman Islands',
  KZ: 'Kazakhstan',
  LA: "Lao People's Democratic Republic",
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libyan Arab Jamahiriya',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MF: 'Saint Martin (French Part)',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'Macedonia, The Former Yugoslav Republic Of',
  ML: 'Mali',
  MM: 'Burma',
  MN: 'Mongolia',
  MO: 'Macao',
  MP: 'Northern Mariana Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  OM: 'Oman',
  OS: 'South Ossetia',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  PN: 'Pitcairn',
  PR: 'Puerto Rico',
  PS: 'Palestinian Territory, Occupied',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russian Federation',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SH: 'Saint Helena, Ascension And Tristan Da Cunha',
  SI: 'Slovenia',
  SJ: 'Svalbard and Jan Mayen',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'South Sudan',
  ST: 'Sao Tome and Principe',
  SV: 'El Salvador',
  SX: 'Sint Maarten',
  SY: 'Syrian Arab Republic',
  SZ: 'Swaziland',
  TC: 'Turks and Caicos Islands',
  TD: 'Chad',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan, Province of China',
  TZ: 'Tanzania, United Republic Of',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VA: 'Holy See (Vatican City State)',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela',
  VG: 'Virgin Islands, British',
  VI: 'Virgin Islands, U.S.',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis and Futuna',
  WS: 'Samoa',
  YE: 'Yemen',
  YT: 'Mayotte',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};
